/*
 * CPU PageRank — reads CSR graph generated by agile_graph_gen,
 * computes PageRank via iterative SpMV with column-normalised weights,
 * and saves the result as a binary float array.
 *
 * This serves as ground-truth for verifying GPU PageRank implementations
 * (AGILE, BAM, GPU-memory).
 */

#include <cmath>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <unordered_map>
#include <vector>

#include <CLI/CLI.hpp>

/* ── Parse graph-gen .info.txt ─────────────────────────────── */
static std::unordered_map<std::string, std::string>
parse_info(const std::string &path) {
    std::unordered_map<std::string, std::string> kv;
    std::ifstream in(path);
    if (!in) {
        std::cerr << "Cannot open info file: " << path << "\n";
        std::exit(1);
    }
    std::string line;
    while (std::getline(in, line)) {
        auto eq = line.find('=');
        if (eq == std::string::npos) continue;
        std::string key = line.substr(0, eq);
        std::string val = line.substr(eq + 1);
        while (!key.empty() && key.back() == ' ') key.pop_back();
        while (!val.empty() && val.front() == ' ') val.erase(val.begin());
        kv[key] = val;
    }
    return kv;
}

/* ── Read offsets (4 or 8 bytes on disk → uint64_t) ────────── */
static std::vector<uint64_t>
read_offsets(const std::string &path, uint64_t count, unsigned int elem_size) {
    std::ifstream in(path, std::ios::binary);
    if (!in) {
        std::cerr << "Cannot open offsets file: " << path << "\n";
        std::exit(1);
    }
    std::vector<uint64_t> offsets(count);
    if (elem_size == 8) {
        in.read(reinterpret_cast<char *>(offsets.data()), count * 8);
    } else if (elem_size == 4) {
        std::vector<uint32_t> tmp(count);
        in.read(reinterpret_cast<char *>(tmp.data()), count * 4);
        for (uint64_t i = 0; i < count; ++i)
            offsets[i] = tmp[i];
    } else {
        std::cerr << "Unsupported offset_size: " << elem_size << "\n";
        std::exit(1);
    }
    return offsets;
}

/* ── Read neighbors (4 or 8 bytes on disk → uint32_t) ──────── */
static std::vector<uint32_t>
read_neighbors(const std::string &path, uint64_t count, unsigned int elem_size) {
    std::ifstream in(path, std::ios::binary);
    if (!in) {
        std::cerr << "Cannot open neighbors file: " << path << "\n";
        std::exit(1);
    }
    std::vector<uint32_t> neighbors(count);
    if (elem_size == 4) {
        in.read(reinterpret_cast<char *>(neighbors.data()), count * 4);
    } else if (elem_size == 8) {
        std::vector<uint64_t> tmp(count);
        in.read(reinterpret_cast<char *>(tmp.data()), count * 8);
        for (uint64_t i = 0; i < count; ++i)
            neighbors[i] = static_cast<uint32_t>(tmp[i]);
    } else {
        std::cerr << "Unsupported node_id_size: " << elem_size << "\n";
        std::exit(1);
    }
    return neighbors;
}

/* ── Column-normalise: value[j] = 1 / out_degree(neighbor[j]) ── */
static std::vector<float>
compute_col_normalised_values(const std::vector<uint64_t> &offsets,
                              const std::vector<uint32_t> &neighbors,
                              uint32_t nodes) {
    // Count out-degree per node (= number of times each node appears as a source row)
    // In CSR, out_degree[i] = offsets[i+1] - offsets[i]
    // But PageRank uses the *transpose* semantics: value[j] = 1/out_degree(col)
    // where col = neighbors[j].  So we need column counts.
    std::vector<uint32_t> col_count(nodes, 0);
    uint64_t total_edges = offsets[nodes];
    for (uint64_t j = 0; j < total_edges; ++j) {
        col_count[neighbors[j]]++;
    }

    std::vector<float> values(total_edges);
    for (uint64_t j = 0; j < total_edges; ++j) {
        uint32_t col = neighbors[j];
        values[j] = (col_count[col] > 0) ? (1.0f / col_count[col]) : 0.0f;
    }
    return values;
}

/* ── One PageRank SpMV iteration ───────────────────────────── */
static float
pr_spmv_iteration(const std::vector<uint64_t> &offsets,
                  const std::vector<uint32_t> &neighbors,
                  const std::vector<float> &values,
                  const std::vector<float> &vec_in,
                  std::vector<float> &vec_out,
                  uint32_t nodes,
                  float damping) {
    float inv_n = (1.0f - damping) / nodes;
    for (uint32_t i = 0; i < nodes; ++i) {
        float sum = 0.0f;
        uint64_t start = offsets[i];
        uint64_t end   = offsets[i + 1];
        for (uint64_t j = start; j < end; ++j) {
            sum += values[j] * vec_in[neighbors[j]];
        }
        vec_out[i] = damping * sum + inv_n;
    }

    // L2 norm of difference
    double norm = 0.0;
    for (uint32_t i = 0; i < nodes; ++i) {
        double d = vec_out[i] - vec_in[i];
        norm += d * d;
    }
    return static_cast<float>(std::sqrt(norm));
}


int main(int argc, char **argv) {
    CLI::App app{"CPU PageRank — reads graph generated by agile_graph_gen"};

    std::string info_file;
    app.add_option("-i,--info", info_file,
                   "Path to the .info.txt produced by graph-gen");

    std::string output_file = "cpu-pr-result.bin";
    app.add_option("-o,--output", output_file, "Output PageRank result file (binary float32)");

    std::string output_norm_file;
    app.add_option("--output-norm", output_norm_file,
                   "Output column-normalised values file (binary float32)");

    float damping = 0.85f;
    app.add_option("-d,--damping", damping, "Damping factor (default: 0.85)");

    unsigned int max_itr = 50;
    app.add_option("--max-itr", max_itr, "Maximum iterations");

    float error_thresh = 1e-6f;
    app.add_option("--error", error_thresh, "Convergence threshold (L2 norm)");

    // Manual overrides
    std::string offsets_path, neighbors_path;
    uint32_t nodes = 0;
    uint64_t edges = 0;
    unsigned int offset_size = 0, node_id_size = 0;
    app.add_option("--offsets", offsets_path, "Offsets binary file");
    app.add_option("--neighbors", neighbors_path, "Neighbors binary file");
    app.add_option("--nodes", nodes, "Number of nodes");
    app.add_option("--edges", edges, "Number of edges (directed)");
    app.add_option("--offset-size", offset_size, "Bytes per offset element (4 or 8)");
    app.add_option("--node-id-size", node_id_size, "Bytes per neighbor element (4 or 8)");

    CLI11_PARSE(app, argc, argv);

    /* ── Resolve from info file ── */
    if (!info_file.empty()) {
        auto kv = parse_info(info_file);
        auto get = [&](const std::string &key) -> std::string {
            auto it = kv.find(key);
            if (it == kv.end()) {
                std::cerr << "Missing key '" << key << "' in " << info_file << "\n";
                std::exit(1);
            }
            return it->second;
        };

        auto info_dir = std::filesystem::path(info_file).parent_path();

        if (offsets_path.empty()) {
            offsets_path = get("offsets_file");
            if (!offsets_path.empty() && offsets_path[0] != '/' && !info_dir.empty())
                offsets_path = (info_dir / offsets_path).string();
        }
        if (neighbors_path.empty()) {
            neighbors_path = get("neighbors_file");
            if (!neighbors_path.empty() && neighbors_path[0] != '/' && !info_dir.empty())
                neighbors_path = (info_dir / neighbors_path).string();
        }
        if (nodes == 0) nodes = std::stoul(get("num_nodes"));
        if (edges == 0) {
            auto it = kv.find("num_edges_directed");
            edges = (it != kv.end()) ? std::stoull(it->second)
                                     : std::stoull(get("num_edges"));
        }
        if (offset_size == 0) offset_size = std::stoul(get("offset_size"));
        if (node_id_size == 0) node_id_size = std::stoul(get("node_id_size"));
    }

    if (offsets_path.empty() || neighbors_path.empty() || nodes == 0) {
        std::cerr << "Provide --info or --offsets, --neighbors, --nodes, etc.\n";
        return 1;
    }
    if (offset_size == 0) offset_size = 4;
    if (node_id_size == 0) node_id_size = 4;

    std::cout << "nodes:              " << nodes << "\n"
              << "edges:              " << edges / 2 << "\n"
              << "edges (directed):   " << edges << "\n"
              << "offset_size:        " << offset_size << "\n"
              << "node_id_size:       " << node_id_size << "\n"
              << "offsets:            " << offsets_path << "\n"
              << "neighbors:          " << neighbors_path << "\n"
              << "damping:            " << damping << "\n"
              << "max_itr:            " << max_itr << "\n"
              << "error_thresh:       " << error_thresh << "\n"
              << "output:             " << output_file << "\n";

    /* ── Load graph ── */
    std::cout << "Loading offsets...\n";
    auto offsets = read_offsets(offsets_path, nodes + 1, offset_size);

    std::cout << "Loading neighbors...\n";
    auto neighbors = read_neighbors(neighbors_path, edges, node_id_size);

    /* ── Compute column-normalised values ── */
    std::cout << "Computing column-normalised values...\n";
    auto values = compute_col_normalised_values(offsets, neighbors, nodes);

    /* ── Optionally save normalised values ── */
    if (!output_norm_file.empty()) {
        std::ofstream norm_out(output_norm_file, std::ios::binary);
        norm_out.write(reinterpret_cast<const char *>(values.data()),
                       values.size() * sizeof(float));
        norm_out.close();
        std::cout << "Normalised values saved to " << output_norm_file << "\n";
    }

    /* ── Run PageRank ── */
    std::cout << "Running PageRank...\n";
    float init_val = 1.0f / nodes;
    std::vector<float> vec(nodes, init_val);
    std::vector<float> out_vec(nodes);

    unsigned int itr = 0;
    float norm = 0.0f;
    auto t0 = std::chrono::high_resolution_clock::now();
    do {
        norm = pr_spmv_iteration(offsets, neighbors, values, vec, out_vec,
                                 nodes, damping);
        std::swap(vec, out_vec);
        std::cout << "itr " << itr << "  norm=" << norm << "\n";
        itr++;
    } while (itr < max_itr && norm > error_thresh);
    auto t1 = std::chrono::high_resolution_clock::now();

    double elapsed =
        std::chrono::duration_cast<std::chrono::duration<double>>(t1 - t0).count();
    std::cout << "PageRank done in " << elapsed << " s  (" << itr << " iterations)\n";

    /* ── Stats ── */
    float max_val = 0, min_val = 1;
    for (uint32_t i = 0; i < nodes; ++i) {
        if (vec[i] > max_val) max_val = vec[i];
        if (vec[i] < min_val) min_val = vec[i];
    }
    std::cout << "min=" << min_val << "  max=" << max_val << "\n";

    /* ── Save result ── */
    {
        std::ofstream ofs(output_file, std::ios::binary);
        ofs.write(reinterpret_cast<const char *>(vec.data()),
                  nodes * sizeof(float));
        ofs.close();
    }
    std::cout << "Result saved to " << output_file << "\n";

    return 0;
}
