#include <chrono>
#include <cstring>
#include <fstream>
#include <iostream>
#include <queue>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

#include <CLI/CLI.hpp>

// ---------------------------------------------------------------------------
// Parse a graph-gen .info.txt file into key-value pairs.
// Format per line:  "key= value"
// ---------------------------------------------------------------------------
static std::unordered_map<std::string, std::string>
parse_info(const std::string &path) {
    std::unordered_map<std::string, std::string> kv;
    std::ifstream in(path);
    if (!in) {
        std::cerr << "Cannot open info file: " << path << "\n";
        std::exit(1);
    }
    std::string line;
    while (std::getline(in, line)) {
        auto eq = line.find('=');
        if (eq == std::string::npos) continue;
        std::string key = line.substr(0, eq);
        std::string val = line.substr(eq + 1);
        // trim spaces
        while (!key.empty() && key.back() == ' ') key.pop_back();
        while (!val.empty() && val.front() == ' ') val.erase(val.begin());
        kv[key] = val;
    }
    return kv;
}

// ---------------------------------------------------------------------------
// Read the offsets array.  offset_size may be 4 or 8.
// We always return a vector<uint64_t> so the BFS loop can use 64-bit indexing.
// ---------------------------------------------------------------------------
static std::vector<uint64_t>
read_offsets(const std::string &path, uint64_t count, unsigned offset_size) {
    std::ifstream in(path, std::ios::binary);
    if (!in) {
        std::cerr << "Cannot open offsets file: " << path << "\n";
        std::exit(1);
    }
    std::vector<uint64_t> offsets(count);
    if (offset_size == 8) {
        // Direct read into uint64_t
        in.read(reinterpret_cast<char *>(offsets.data()),
                count * sizeof(uint64_t));
    } else if (offset_size == 4) {
        // Read as uint32_t then widen
        std::vector<uint32_t> tmp(count);
        in.read(reinterpret_cast<char *>(tmp.data()),
                count * sizeof(uint32_t));
        for (uint64_t i = 0; i < count; ++i)
            offsets[i] = tmp[i];
    } else {
        std::cerr << "Unsupported offset_size: " << offset_size << "\n";
        std::exit(1);
    }
    return offsets;
}

// ---------------------------------------------------------------------------
// Read the neighbors (edge) array.  node_id_size may be 4 or 8.
// We always return a vector<uint32_t> (node IDs fit in 32 bits for practical
// graphs; extend to 64 if needed).
// ---------------------------------------------------------------------------
static std::vector<uint32_t>
read_neighbors(const std::string &path, uint64_t count,
               unsigned node_id_size) {
    std::ifstream in(path, std::ios::binary);
    if (!in) {
        std::cerr << "Cannot open neighbors file: " << path << "\n";
        std::exit(1);
    }
    std::vector<uint32_t> neighbors(count);
    if (node_id_size == 4) {
        in.read(reinterpret_cast<char *>(neighbors.data()),
                count * sizeof(uint32_t));
    } else if (node_id_size == 8) {
        std::vector<uint64_t> tmp(count);
        in.read(reinterpret_cast<char *>(tmp.data()),
                count * sizeof(uint64_t));
        for (uint64_t i = 0; i < count; ++i)
            neighbors[i] = static_cast<uint32_t>(tmp[i]);
    } else {
        std::cerr << "Unsupported node_id_size: " << node_id_size << "\n";
        std::exit(1);
    }
    return neighbors;
}

// ---------------------------------------------------------------------------
// BFS  (level-synchronous, identical semantics to cpu_verify/bfs)
// ---------------------------------------------------------------------------
static void bfs(const std::vector<uint64_t> &offsets,
                const std::vector<uint32_t> &neighbors,
                std::vector<uint32_t> &levels, uint32_t start,
                uint32_t &visited_out, uint32_t &depth_out) {
    std::memset(levels.data(), 0xFF, levels.size() * sizeof(uint32_t));
    // 0xFFFFFFFF == (uint32_t)-1, used as "unvisited"

    uint32_t visited = 0, level = 0;
    std::queue<uint32_t> cur, nxt;
    cur.push(start);

    while (!cur.empty()) {
        while (!cur.empty()) {
            uint32_t v = cur.front();
            cur.pop();
            if (levels[v] != UINT32_MAX) continue;  // already visited
            ++visited;
            levels[v] = level;
            for (uint64_t e = offsets[v]; e < offsets[v + 1]; ++e)
                nxt.push(neighbors[e]);
        }
        ++level;
        std::swap(cur, nxt);
    }
    visited_out = visited;
    depth_out = level;
}

int main(int argc, char **argv) {
    CLI::App app{"CPU BFS — reads graph generated by agile_graph_gen"};

    std::string info_file;
    std::string output_file = "cpu-bfs-result.bin";
    uint32_t start_node = 0;

    // Allow the user to supply either --info (auto-resolve everything) or
    // manual overrides.
    std::string offsets_file, neighbors_file;
    uint64_t node_num = 0, edge_num = 0, edge_num_directed = 0;
    unsigned offset_size = 0, node_id_size = 0;

    app.add_option("-i,--info", info_file,
                   "Path to the .info.txt produced by graph-gen");
    app.add_option("-o,--output", output_file, "Output BFS result file")
        ->default_str(output_file);
    app.add_option("-s,--start", start_node, "Start node for BFS")
        ->default_val(0);

    // Manual overrides (only needed when no --info)
    app.add_option("--offsets", offsets_file, "Offsets binary file");
    app.add_option("--neighbors", neighbors_file, "Neighbors binary file");
    app.add_option("--nodes", node_num, "Number of nodes");
    app.add_option("--edges", edge_num, "Number of edges");
    app.add_option("--offset-size", offset_size,
                   "Bytes per offset element (4 or 8)");
    app.add_option("--node-id-size", node_id_size,
                   "Bytes per neighbor element (4 or 8)");

    CLI11_PARSE(app, argc, argv);

    // ── Resolve parameters from info file if provided ──
    if (!info_file.empty()) {
        auto kv = parse_info(info_file);

        auto get = [&](const std::string &key) -> std::string {
            auto it = kv.find(key);
            if (it == kv.end()) {
                std::cerr << "Missing key '" << key << "' in " << info_file
                          << "\n";
                std::exit(1);
            }
            return it->second;
        };

        if (offsets_file.empty()) offsets_file = get("offsets_file");
        if (neighbors_file.empty()) neighbors_file = get("neighbors_file");
        if (node_num == 0) node_num = std::stoull(get("num_nodes"));
        if (edge_num == 0) edge_num = std::stoull(get("num_edges"));
        // The CSR stores directed edge entries; for undirected graphs this
        // is 2x num_edges.  Use num_edges_directed when available.
        if (edge_num_directed == 0) {
            auto it = kv.find("num_edges_directed");
            edge_num_directed = (it != kv.end())
                                    ? std::stoull(it->second)
                                    : edge_num;
        }
        if (offset_size == 0) offset_size = std::stoul(get("offset_size"));
        if (node_id_size == 0) node_id_size = std::stoul(get("node_id_size"));
    }

    // Validate
    if (edge_num_directed == 0) edge_num_directed = edge_num;
    if (offsets_file.empty() || neighbors_file.empty() || node_num == 0 ||
        edge_num_directed == 0 || offset_size == 0 || node_id_size == 0) {
        std::cerr << "Provide --info or all manual parameters "
                     "(--offsets, --neighbors, --nodes, --edges, "
                     "--offset-size, --node-id-size)\n";
        return 1;
    }

    std::cout << "nodes:              " << node_num << "\n"
              << "edges:              " << edge_num << "\n"
              << "edges (directed):   " << edge_num_directed << "\n"
              << "offset_size:        " << offset_size << "\n"
              << "node_id_size:       " << node_id_size << "\n"
              << "offsets:            " << offsets_file << "\n"
              << "neighbors:          " << neighbors_file << "\n"
              << "start_node:         " << start_node << "\n"
              << "output:             " << output_file << "\n";

    if (start_node >= node_num) {
        std::cerr << "start_node " << start_node << " >= node_num " << node_num
                  << "\n";
        return 1;
    }

    // ── Load graph ──
    std::cout << "Loading offsets...\n";
    auto offsets = read_offsets(offsets_file, node_num + 1, offset_size);

    std::cout << "Loading neighbors...\n";
    auto neighbors =
        read_neighbors(neighbors_file, edge_num_directed, node_id_size);

    // ── Run BFS ──
    std::vector<uint32_t> levels(node_num);
    uint32_t visited = 0, depth = 0;

    std::cout << "Running BFS from node " << start_node << "...\n";
    auto t0 = std::chrono::high_resolution_clock::now();
    bfs(offsets, neighbors, levels, start_node, visited, depth);
    auto t1 = std::chrono::high_resolution_clock::now();

    double elapsed_ms =
        std::chrono::duration_cast<std::chrono::microseconds>(t1 - t0).count() /
        1000.0;

    std::cout << "BFS done in " << elapsed_ms << " ms\n"
              << "  visited: " << visited << "\n"
              << "  depth:   " << depth << "\n";

    // ── Write result ──
    std::ofstream out(output_file, std::ios::binary);
    if (!out) {
        std::cerr << "Cannot write to " << output_file << "\n";
        return 1;
    }
    out.write(reinterpret_cast<const char *>(levels.data()),
              levels.size() * sizeof(uint32_t));
    out.close();
    std::cout << "Result saved to " << output_file << "\n";

    return 0;
}
